export enum CART {
  ORDERED_PLACED = "ORDERED PLACED",
  PROCESSING = "PROCESSING",
  DISPATCH = "DISPATCH",
  DELIVERED = "DELIVERED",
  UNABLE_PROCESSING = "UNABLE PROCESSING",
  DISPATCH_DELAY = "DISPATCH DELAY",
  CANCELLED = "CANCELLED",
}

export enum WISHLIST{
  CART_WISHLIST="CART WISHLIST"
}